### ISSUE TITLE
exception/error 500 when adding an aircraft without aircraft ICAO code

### ISSUE THREAD

**Issue by xplana** [MultiCrew/copilot#172] opened 2020-12-25 11:18 UTC
**Describe the bug**
As title

**To Reproduce**
- Create a new aircraft in "FLEET" menu
- enter aircraft data without ICAO code ( in my example no icao code for TBM900 provided/found)
- click "submit" button
- error 500 hows up (see picture below) 

**Expected behavior**
A catch/message should be presented stating that process cannot be continued because of the missing ICAO code.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17392829/103133420-9bf76b00-46aa-11eb-878b-1235da6d2b6a.png)
![grafik](https://user-images.githubusercontent.com/17392829/103133473-f09ae600-46aa-11eb-9111-f9b2270cd2a4.png)

**Desktop (please complete the following information):**
 - OS: latest WIN 10
 - Browser [latest firefox]

**Comment by calumshep** [comment] 2020-12-25 11:20
Duplicate of #171 (I just submitted it after our error reporting software flagged this issue up before you had time to do a bug report!). Thanks though!

**Closed as completed by calumshep** 2020-12-25 11:20 UTC
Labels: bug, duplicate
